### ISSUE TITLE
Any separate usb driver required for windows 10?

### ISSUE THREAD

**Issue by whatdtech** [m3y54m/pcb-esp32-s3-wroom-1-breakout-board#2]
While connecting as per your schematic GPIO 19/20 to D-/D+,  getting error "UNKNOWN USB DEVICE(DEVICE DESCRIPTOR FAILED)". Any reference for using USB without traditional Rx/TX oins

**Comment by m3y54m** [comment]
I'm not sure, but I think drivers are installed with ESP-IDF. But It seems that the error "UNKNOWN USB DEVICE(DEVICE DESCRIPTOR FAILED)" is because of wrong wiring. Are you sure that you connected D+ and D- correctly?

> Any reference for using USB without traditional Rx/TX pins

What do you want exactly do with USB?

In ESP32-S3 you can use only UART0 (RXD0 / TXD0) for programming. Which is done through a USB to UART converter.
But if you want a real USB port (not a UART port converted to USB) you should use only GPIO 19/20 pins. No other options.
